id: P009659
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:43:16.105130
source_metadata:
  id: bdr:W1KG9263
  title: གེ་སར་དང་རོ་སྒྲུང་སོགས་གནའ་བོའི་བོད་ཀྱི་སྒྲུང་།
  author: ''
  volumes:
    05a1a7b8213a4ecea5f5915510738d5a:
      image_group_id: I1KG9528
      title: ''
      volume_number: 1
      total_pages: 93
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
