id: I3B99930D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:10:41+00:00'
last_modified: '2022-06-08T12:38:00.024614+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9263
  title: གེ་སར་དང་རོ་སྒྲུང་སོགས་གནའ་བོའི་བོད་ཀྱི་སྒྲུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    '2804':
      image_group_id: I1KG9528
      title: ''
      total_pages: 93
      order: 1
      base_file: 2804.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
